Fixed grammar and spelling
alpacahq/alpaca-trade-api-python pull request #629
Opened 2022-06-20 00:05 UTC by ALifeLivedFully

Lines 22, 26, 76, and 225.

2022-06-20 04:54 UTC, haxdds requested changes
Thanks for contributing! @ALifeLivedFully 

Just one small comment

2022-06-20 04:54 UTC, haxdds commented on README.md
> +The solution - manually install these package's before installing alpaca-trade-api. e.g:
```suggestion
The solution - manually install these packages before installing alpaca-trade-api. e.g:
```

2022-06-20 04:54 UTC, haxdds commented on README.md
> +The solution - manually install these package's before installing alpaca-trade-api. e.g:
should be plural instead of possessive

2022-06-20 14:50 UTC, ALifeLivedFully commented on README.md
> +The solution - manually install these package's before installing alpaca-trade-api. e.g:
Good catch!

2022-06-21 04:23 UTC, haxdds approved these changes
Thank you

2022-06-21 04:23 UTC, merged